service: notes-app-api
# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack
# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true
provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-1
  iamRoleStatements: #permission for all of your functions can be set here
  - Effect: Allow
    Action:       # Gives permission to DynamoDB tables in a specific region
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource: "arn:aws:dynamodb:us-east-1:*:*"
# 'iamRoleStatement' defines the permission policy for the Lambda function.
# In this case Lambda functions are granted with permissions to access DynamoDB.


functions:
  # Defines an HTTP API endpoint that calls the main function in create.js
     # - path: url path is /notes
     # - method: POST request
     # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
  # domain api call
  # - authorizer: authenticate using the AWS IAM role
  create:
    handler: create.main
    events:
      - http:
          path: notes
          method: post
          cors: true
          authorizer: aws_iam
